Django/dbautosal/dbautosal/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  auth_views.LoginView.as_view(template_name='registration/login.html',redirect_authenticated_user=True), name="login"),
    url(r'^',include('dbpagesal.urls',namespace="dbpagesal")),
]

Django/dbautosal/dbpagesal/urls.py
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_viewsfrom .import views

app_name = "dbpagesal"
#print("y")
urlpatterns = [
#     path('', views.index, name='login'),
    url(r'^index/$',views.index,name="index"), 
    url(r'^verify/$',views.verify,name="verify"), 
    url(r'^info/$',views.info,name="info"),
    url(r'^detail/$',views.detail,name="detail"),
    url(r'^complete/$',views.complete,name="complete"),
]

Django/dbautosal/dbpagesal/models.py
from django.db import models

# Create your models here.

Django/dbautosal/dbpagesal/views.py
from django.shortcuts import render
import cx_Oracle
import configparser
from django.contrib.auth import views as auth_views
from django.http import HttpResponse,HttpResponseRedirect
from .filehandle import readcsv
from django.http import JsonResponse


config = configparser.RawConfigParser()
config.read('C:/Users/salsabil.ahmad/Desktop/connection.properties')
uimusername = config.get('UIMDatabase', 'username');
print(uimusername)
uimpassword = config.get('UIMDatabase', 'password');
uimdbdetails = config.get('UIMDatabase', 'dbconnection');
osmusername = config.get('OSMDatabase', 'username');
print(osmusername)
osmpassword = config.get('OSMDatabase', 'password');
osmdbdetails = config.get('OSMDatabase', 'dbconnection');



def index(request):
#     if request.user.is_authenticated():
    if "GET" == request.method:
        return render(request, 'dbpagesal/dbcon.html', {})
    else:
        fro= [request.POST.get('fromdate')]
        print(fro)
        to= [request.POST.get('todate')]
        print(to)
        sqlquery="SELECT ENTITYID FROM UIM.SERVICE WHERE SPECIFICATION= '27150055' AND ADMINSTATE='IN_SERVICE' AND CREATEDDATE BETWEEN '%s' and '%s'"%(fro[0], to[0])
        print(sqlquery)
        con = cx_Oracle.connect(uimusername+'/'+uimpassword+'@'+uimdbdetails)
        cur = con.cursor()
        cur.execute("SELECT ENTITYID FROM UIM.SERVICE WHERE SPECIFICATION= '27150055' AND ADMINSTATE='IN_SERVICE' AND CREATEDDATE BETWEEN '%s' and '%s'"%(fro[0], to[0]))
        res = cur.fetchall() 
        cur.close()
        #print (res)
        find=[]
        mylist=[]
        coun=[]
        #success=[]
        count=0
        for i in res:
            count=count+1
            cur=con.cursor()
            #sql="SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONVERSION WHERE SERVICE in '%s' AND VERSIONNUMBER=(SELECT MAX(VERSIONNUMBER) FROM UIM.SERVICECONFIGURATIONVERSION where SERVICE in '%s')"%(i[0],i[0])
            #print(sql)
            #print(i[0])
            cur.execute("SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONVERSION WHERE SERVICE in '%s' AND VERSIONNUMBER=(SELECT MAX(VERSIONNUMBER) FROM UIM.SERVICECONFIGURATIONVERSION where SERVICE in '%s')"%(i[0],i[0]))
            fe = cur.fetchall()
            cur.execute("SELECT ENTITYID FROM UIM.SERVICEASSIGNMENT where SERVICECONSUMER in '%s'"%i[0])
            re = cur.fetchall()
            # print(res)
            voice=[]
            wifi=[]
            out='Success'
            for j in re:
                cur.execute("SELECT ENTITYID,ID, NAME FROM UIM.SERVICE WHERE CURRENTASSIGNMENT in '%s'"%j[0])
                fet=cur.fetchall()
                # print(fet)
                cur.execute("SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONVERSION WHERE SERVICE in '%s' AND VERSIONNUMBER=(SELECT MAX(VERSIONNUMBER) FROM UIM.SERVICECONFIGURATIONVERSION where SERVICE in '%s')"%(fet[0][0],fet[0][0]))
                got=cur.fetchall()
                # print(got)
               
                print(fet[0][2])
                if "Mobile_Account_RFS" in fet[0][2]:
                    cur.execute("SELECT DISTINCT NAME, VALUE FROM UIM.SERVICECONFIGITEM_CHAR WHERE CHAROWNER in (SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONITEM where NAME='Properties' AND CONFIGURATION in (%s,%s)) AND VALUE not in ('Value Not Set','Not Available')"%(fe[0][0],got[0][0]))
                    ans=cur.fetchall()
                    out=readcsv(ans,"Mobile_Account_RFS")
                    # print(ans)
                    print(out)
                    #return render(request, 'dbpagesal/respage.html', {'result':ans})
                elif "WIFI_Access_RFS" in fet[0][2]:
                    cur.execute("SELECT NAME, VALUE FROM UIM.SERVICECONFIGITEM_CHAR WHERE CHAROWNER in (SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONITEM where NAME='Properties' AND CONFIGURATION in '%s') AND VALUE not in ('Value Not Set','Not Available')"%got[0][0])
                    wifi=cur.fetchall()
                    out=readcsv(wifi,"WIFI_Access_RFS")
                    # print(wifi)
                    print(out)
                    #return render(request, 'dbpagesal/respage.html', {'resultw':wifi})
                elif "Voicemail_Service_RFS" in fet[0][2]:
                    cur.execute("SELECT NAME, VALUE FROM UIM.SERVICECONFIGITEM_CHAR WHERE CHAROWNER in (SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONITEM where NAME='Properties' AND CONFIGURATION in '%s') AND VALUE not in ('Value Not Set','Not Available')"%got[0][0])
                    voice=cur.fetchall()
                    out=readcsv(voice,"Voicemail_Service_RFS")
                    # print(voice)
                    print(out)
                    #return render(request, 'dbpagesal/respage.html', {'resultv':voice})
                #print(fet[0][0])
         
            # sql = "SELECT UIM.SERVICE.ID as Service_ID, UIM.BUSINESSINTERACTION.EXTERNALNAME as Order_ID, UIM.SERVICE.ADMINSTATE as Status FROM UIM.SERVICE CROSS JOIN UIM.BUSINESSINTERACTION WHERE  UIM.SERVICE.ENTITYID='%s' and UIM.BUSINESSINTERACTION.ENTITYID in(SELECT BUSINESSINTERACTION FROM UIM.BUSINESSINTERACTIONITEM where TOENTITYREF='%s')"%(i[0],fet[0][0])
            #print(sql)
            cur.execute("SELECT UIM.SERVICE.ENTITYID as ENTITYID, UIM.SERVICE.ID as Service_ID, UIM.BUSINESSINTERACTION.EXTERNALNAME as Order_ID,UIM.SERVICE.ADMINSTATE as Status FROM UIM.SERVICE CROSS JOIN UIM.BUSINESSINTERACTION WHERE UIM.SERVICE.ENTITYID='%s' and UIM.BUSINESSINTERACTION.ENTITYID in (SELECT BUSINESSINTERACTION FROM UIM.BUSINESSINTERACTIONITEM where TOENTITYREF='%s' AND ENTITYCLASS='BusinessInteractionItemDAO')"%(i[0],fe[0][0]))
            find = cur.fetchall()
            if str(out)=='Success':
                find.append('PASSED')
            else:
                find.append('FAILED')
            # find.append(success)
            print(find)
            mylist.append(find)
            print(mylist)
        coun.append(count)   
        return render(request, 'dbpagesal/dbcon.html', {'result':mylist,'coin':count,'fromd':fro,'tod':to})
        cur.close()
        con.close()   
      
def verify(request):
    if "GET" == request.method:
        return render(request, 'dbpagesal/respage.html', {})
        # return render(request, 'dbpagesal/orderpage.html', {})
    else:
        id= request.POST.get('name')
        print(id)
        con = cx_Oracle.connect(uimusername+'/'+uimpassword+'@'+uimdbdetails)
        cur = con.cursor()
        cur.execute("SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONVERSION WHERE SERVICE in '%s' AND VERSIONNUMBER=(SELECT MAX(VERSIONNUMBER) FROM UIM.SERVICECONFIGURATIONVERSION where SERVICE in '%s')"%(id,id))
        re=cur.fetchall()
        cur.execute("SELECT ENTITYID FROM UIM.SERVICEASSIGNMENT where SERVICECONSUMER in '%s'"%id)
        res = cur.fetchall()
        print(res)
        voice=[]
        wifi=[]
        ans=[]
        for i in res:
            cur.execute("SELECT ENTITYID,ID, NAME FROM UIM.SERVICE WHERE CURRENTASSIGNMENT in '%s'"%i[0])
            fet=cur.fetchall()
            print(fet)
            cur.execute("SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONVERSION WHERE SERVICE in '%s' AND VERSIONNUMBER=(SELECT MAX(VERSIONNUMBER) FROM UIM.SERVICECONFIGURATIONVERSION where SERVICE in '%s')"%(fet[0][0],fet[0][0]))
            got=cur.fetchall()
            print(got)
            print(fet[0][2])
            if "Mobile_Account_RFS" in fet[0][2]:
                cur.execute("SELECT DISTINCT NAME, VALUE FROM UIM.SERVICECONFIGITEM_CHAR WHERE CHAROWNER in (SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONITEM where NAME='Properties' AND CONFIGURATION in (%s,%s)) AND VALUE not in ('Value Not Set','Not Available') order by NAME"%(re[0][0],got[0][0]))
                ans=cur.fetchall()
                print(ans)
                #return render(request, 'dbpagesal/respage.html', {'result':ans})
            elif "WIFI_Access_RFS" in fet[0][2]:
                cur.execute("SELECT NAME, VALUE FROM UIM.SERVICECONFIGITEM_CHAR WHERE CHAROWNER in (SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONITEM where NAME='Properties' AND CONFIGURATION in '%s') AND VALUE not in ('Value Not Set','Not Available')"%got[0][0])
                wifi=cur.fetchall()
                print(wifi)
                #return render(request, 'dbpagesal/respage.html', {'resultw':wifi})
            elif "Voicemail_Service_RFS" in fet[0][2]:
                cur.execute("SELECT NAME, VALUE FROM UIM.SERVICECONFIGITEM_CHAR WHERE CHAROWNER in (SELECT ENTITYID FROM UIM.SERVICECONFIGURATIONITEM where NAME='Properties' AND CONFIGURATION in '%s') AND VALUE not in ('Value Not Set','Not Available')"%got[0][0])
                voice=cur.fetchall()
                print(voice)
                #return render(request, 'dbpagesal/respage.html', {'resultv':voice})
        return render(request, 'dbpagesal/respage.html', {'resultm':ans,'resultw':wifi,'resultv':voice})
        cur.close()
        con.close()

def info(request):
    if "GET" == request.method:
        return render(request, 'dbpagesal/orderpage.html', {})
    else:
        Oid= request.POST.get('Order')
        print(Oid)
        con = cx_Oracle.connect(osmusername+'/'+osmpassword+'@'+osmdbdetails)
        cur=con.cursor()
        q="SELECT order_seq_id as Order ID,ORD_TXN_REASON as Order Status FROM OM_ORDER_HEADER where REFERENCE_NUMBER='%s'"%Oid
        print(q)
        cur.execute("SELECT order_seq_id as OrderID,ORD_TXN_REASON as Order_Status,REFERENCE_NUMBER FROM OM_ORDER_HEADER where REFERENCE_NUMBER='%s'"%Oid)
        global RESULT1
        RESULT1=cur.fetchall()
        print(RESULT1)
        return render(request, 'dbpagesal/orderpage.html',{'output':RESULT1})

def detail(request):
    if "GET" == request.method:
        return render(request, 'dbpagesal/orderpage.html', {})
    else:
        Oid= request.POST.get('orderid')
        con = cx_Oracle.connect('ordermgmt/passw0rd@tr001buosm-db.ddc.teliasonera.net:1521/TRBUOSM')
        cur=con.cursor()

Django/dbautosal/dbpagesal/templates/dbpagesal/dbcon.html
<!DOCTYPE html>
<html>
<head>
    <title>Model Page</title>
    <meta charset="utf-8"/>
    {% load staticfiles %}
    <link rel='stylesheet' href="{% static 'css/mycss.css' %}" type='text/css'/>
   <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"/>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
    body  {
        width:100%;
        background: url(../static/img.jfif) ;
        background-size:cover;
    }
    </style>
</head> 
<body  class="body">
<h2>UIM Data Validation</h2>

<div class="container">
<!-- <div class="row container-1"> -->

<form id="searchresult_frm1" action="{% url "dbpagesal:info" %}" method="POST">
{% csrf_token %}
<div class=" col-3">
<input id="searchBar" name="Order" class="searchbar" type="search" placeholder="Order Id">
 <button type="submit" id="submit" class="btn-search">
    <i class="fa fa-search"></i>
  </button> 
<!--  <a id="btnSearch" class="btn-search"><i class="fa fa-search"></i></a>  -->
  </div>
 </form>
<!--  </div> -->

<!--   <div class="row1"> 
    <div class="col-3 input-effect"> 
        <input class="effect-21" type="text" name="Order" placeholder="" />
        <label>Order ID</label>
        <span class="focus-border"> <i></i> </span>
	</div>
					
	<div class="col-3">
        <input type="submit"  class="btn-primary btn-form" value="Search" id="searchresult_btn">
    </div> 
</div>
 </form> -->
<form id="searchresult_frm" action="{% url "dbpagesal:index" %}" method="POST">
{% csrf_token %}

<div class="row">

				<div class="col-3 input-effect">
					<input class="effect-21" type="text" name="fromdate" placeholder="" /> <label>From Date</label> <span
						class="focus-border"> <i></i>
					</span>
				</div>

				<div class="col-3 input-effect">

					<input type="text" name="todate" class="effect-21" placeholder="" />
					<label>To Date</label> <span class="focus-border"> <i></i>
					</span>
				</div>

				<!-- <div class="col-3">
					<input type="submit" class="btn-primary btn-form" value="Submit"
						id="searchresult_btn">
				</div> -->

				<div class="col-3">
					<input type="submit" class="btn-primary btn-form" value="Submit"
						id="searchresult_btn">
				</div>
			</div>
</form> 

<p class="preload"><b><i>Between Dates : {% for k in fromd %} {{k}}{%endfor%} - {% for j in tod %} {{j}}{%endfor%} </i></b></p>
<div class="center quote">
<h1></h1>
</div>
<div class="showtable preload" >

<table class="center tbl-header" cellpadding="0" cellspacing="0"
			border="0">
			<thead class="thead-dark">
				<tr>
					<th scope="col">ENTITY ID</th>
					<th scope="col">Service ID</th>
					<th scope="col">Order ID</th>
					<th scope="col">Status</th>
					<th scope="col">validation</th>
					<th scope="col">verification</th>
				</tr>
			</thead>
		</table>
		
		<div id="loading">
		<img id="loading-image" src="../static/img/ajax-loader2.gif" alt="Loading..." /> 	
	</div> 
	
	<div class="center tbl-content " id="searchresult">
		<table id="tableshow"class="center1 table-hover" cellpadding="0" cellspacing="0" border="0">
                {% for i in result %}
				<tr>
                {% for j in i|slice:"1" %}
                {% for k in j %}
                    <td><b>{{k}}</b></td> {% endfor %}
                    <td>{% ifequal i.1 "PASSED" %}
                        <b style="background-color:rgba(81, 255, 0, 0.753)">{{i.1}}</b>
                        {% else %}
                        <b style="background-color:rgb(255, 61, 47)">{{i.1}}</b>
                        {% endifequal %}
                    </td>
					<td>
						<form action="{% url "dbpagesal:verify" %}" method="POST">
							{% csrf_token %}
							<button type="submit" value="{{j.0}}" name="name" autofocus>verify</button>
                    </td>
                {% endfor %}
				</tr>
				{% endfor %}
		</table>
	   </div>
    <p class="preload">Number of Orders: {{coin}}</p>
    </div>
   </div> 
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script>
		$(window).load(function() {
			/* $(".col-3 input").val(""); */
			$(".input-effect input").focusout(function() {
				if ($(this).val() != "") {
					$(this).addClass("has-content");
				} else {
					$(this).removeClass("has-content");
				}
			})
			
			
			var tbody = $("#tableshow tbody");

if (tbody.children().length !== 0) {
	 $("div").removeClass("preload");
	 $("p").removeClass("preload");
	 $(".quote").addClass("preload");
}
		});
	</script>
	<script language="javascript" type="text/javascript">
		$('#searchresult_frm').submit(function() {
			
			$('#loading').show();
			 $("div").removeClass("preload");
			 $(".quote").addClass("preload");
		});
		$(window).load(function() {
			$('#loading').hide();
			
		});
		
	</script>
	
<script>
	var quotes = [
  "UIM Order Details and Validation.",
  "UIM Order Status.",
  "Bulk Order Validation."
];

// variable to keep track of last quote displayed
var i = 0;

// displays the next quote in the array
var quoteTimer = function() {
  
  // if at end of array, reset
  if (i >= quotes.length) {
    i = 0;
  }

  // fade out previous quote, 
  // while hidden, change the text to the next quote on the array
  $('h1').fadeOut(1000, function(){
    $(this).text(quotes[i]);
  });
  
  // display the quote
  $('h1').fadeIn();

  // increment counter by one
  i++;
}


$(document).ready(function() {
  $('h1').text(quotes[i++]); // initialize with first quote
  setInterval(quoteTimer, 5000);
});
</script>
</body>
</html>

Django/dbautosal/dbpagesal/templates/dbpagesal/newpage.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    {% load staticfiles %}
  <link rel='stylesheet' href="{% static 'css/mycss.css' %}" type='text/css'/>
   <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"/>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body class="body">
   
   <div class="container">  
    <h3>UIM Data Validation</h3>
<button class ="back-button" onclick="javascript:history.go(-1);">Go Back</button>
		<div class="firstTable">
   <table class="center tbl-header" cellpadding="0" cellspacing="0"
			border="0">
			<thead class="thead-dark">
        <tr>
            <th scope="col">ENTITY ID</th>
            <th scope="col">Service ID</th>
            <th scope="col">Order ID</th>
           <th scope="col">Status</th>
             <th scope="col">validation</th>
            <th scope="col">verification</th>
				</tr>
			</thead>
		</table>

	<div class="center tbl-content1" id="searchresult">
		<table class="center1 table-hover" cellpadding="0" cellspacing="0" border="0">
                {% for i in result %}
				<tr>
                {% for j in i|slice:"1" %}
                {% for k in j %}
                    <td><b>{{k}}</b></td> {% endfor %}
                    <td>{% ifequal i.1 "PASSED" %}
                        <p style="background-color:rgba(81, 255, 0, 0.753)">{{i.1}}</p>
                        {% else %}
                        <p style="background-color:rgb(255, 61, 47)">{{i.1}}</p>
                        {% endifequal %}
                    </td>
					<td>
						<form action="{% url "dbpagesal:verify" %}" method="POST">
							{% csrf_token %}
							<button type="submit" value="{{j.0}}" name="name" autofocus>verify</button>
                    </td>
                {% endfor %}
				</tr>
				{% endfor %}
		</table>
		</div>
		</div>
        
</div>
</body>
</html>

Django/dbautosal/dbpagesal/templates/dbpagesal/orderpage.html
<!DOCTYPE html>
<html>
<head>
<title>Order Page</title>
    <meta charset="utf-8"/>
    {% load staticfiles %}
   <link rel='stylesheet' href="{% static 'css/mycss.css' %}" type='text/css'/>
   <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"/>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head> 
<body  class="body">
     
<div class="container">

 <button class ="back-button" onclick="javascript:history.go(-1);">Go Back</button>
<!--  <input type=button value="Go Back" onClick="javascript:history.go(-1);"> -->
<div class="firstTable">
   <table class="center tbl-header" cellpadding="0" cellspacing="0"
			border="0">
			<thead class="thead-dark">
        <tr>
        <th scope="col">Order ID</th>
        <th scope="col">Order Status</th>
        <th scope="col">Reference Number</th>
        <th scope="col">Order Details</th>
        </tr>
        	</thead>
	</table>
		
		<div class="center tbl-content1" id="searchresult">
		<table class="center1 table-hover" cellpadding="0" cellspacing="0" border="0">
        {% for i in output%}
        <tr>
            {% for j in i %}
            <td>{{j}}</td>
            {% endfor %}
            {% ifequal i.1 "Order submitted"%}
            <td>
                <form id="sub1_frm" action="{% url "dbpagesal:detail" %}" method="POST">
                {% csrf_token %}
                <button  id="sub1" type="submit" value="{{i.2}}" name="orderid" autofocus>order details</button>
            </td>
            {% else %}
            <td>
                    <form id="sub1_frm" action="{% url "dbpagesal:complete" %}" method="POST">
                    {% csrf_token %}
                    <button id="sub1" type="submit" value="{{i.2}}" name="orderid" autofocus>validate order</button>
            </td>
            {% endifequal%}
        </tr>
        {% endfor %}
    </table>
    </div>

      </div>
    <div>
  <div id="secondTable" class="secondTable preload">
    <h3>OSM Order Details</h3>
        <table id="inprogress" class="center tbl-header" cellpadding="0" cellspacing="0"
			border="0">
        <thead class="thead-dark">
				<tr>
        <th scope="col">Order ID</th>
       <th scope="col">Task Name</th>
       <th scope="col">Task Status</th>
        </tr>
        </thead>
		</table>
		
		<div class="center tbl-content1 " id="searchresult">
		<table id="tableshow"class="center1 table-hover" cellpadding="0" cellspacing="0" border="0">
        {% for a in output1 %}
        <tr>
            {% for b in a %}
            {% for c in b %}
            <td>{{c}}</td>
            {% endfor %} {% endfor %}
        </tr>
        {% endfor %}
    </table>
    </div>
    </div>
    </div>

</div>
 <div id="loading">
		<img id="loading-image" src="../static/img/ajax-loader2.gif" alt="Loading..." /> 	
</div> 
<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

	<script>
	 	$(window).load(function() {
	 	$('#loading').hide(); 
			var tbody = $("#tableshow tbody");

if (tbody.children().length !== 0) {
	 $("div").removeClass("preload");
	 $(".firstTable").addClass("preload");
}else {
	
}
		}); 
	 	
 $('#sub1_frm').submit(function() {		
			$('#loading').show();
		}); 
/* $('#sub1_frm').submit(function() {
			
	 $("div").removeClass("preload");
	 		});
		 */
		
	</script>
	
</body>
</html>

Django/dbautosal/dbpagesal/templates/dbpagesal/respage.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<link rel='stylesheet' href="{% static 'css/mycss.css' %}" type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body  {
    width:100%;
    background: url('/static/img.jfif') ;
    background-size:cover; 
}

.accordion {

  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}
.active, .accordion:hover {
  background-color: rgb(144, 207, 248); 
}
.panel {
  padding: 0 18px;
  margin-top: 0px;
  border: 1px solid rgba(255, 255, 255, 0.3);
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}

.accordion:after {
  content: '\02795'; /* Unicode character for "plus" sign (+) */
  font-size: 13px;
  color: #777;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2796"; /* Unicode character for "minus" sign (-) */
}

</style>

</head>
<body class="body">
	<h2>
		Mobile Service and Technical Parameters
	</h2>
 <div class="container">
 <button class ="back-button" onclick="goBack()">Go Back</button>
<button class="accordion"><b>UIM mobile service account parameter</b></button>
	<div id="sub3" class="panel" data-parent="#myAccordion">
			<table class="center tbl-header">
				<thead class="thead-dark">
					<tr>
						<th scope="col">NAME</th>
						<th scope="col">VALUE</th>
					</tr>
				</thead>
			</table>
			<div class="center tbl-content2" id="searchresult">
				<table class="center1 table-hover" cellpadding="0" cellspacing="0">
					{% for i in resultm %}
					<tr>
						{% for j in i %}
						<td>{{j}}</td> {% endfor %}
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
<button class="accordion"><b>UIM wifi account parameter</b></button>
    <div id="sub2" class="panel" data-parent="#myAccordion">
			<table class=" center tbl-header" cellpadding="0" cellspacing="0"
				border="0">
				<thead class="thead-dark">
					<tr>
						<th scope="col">NAME</th>
						<th scope="col">VALUE</th>
					</tr>
				</thead>
			</table>
			<div class="center tbl-content2" id="searchresult">
				<table class="center1 table-hover" cellpadding="0" cellspacing="0">
					{% for i in resultw %}
					<tr>
						{% for j in i %}
						<td>{{j}}</td> {% endfor %}
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
<button class="accordion"><b>UIM voicemail account parameter</b></button>
   <div id="sub1" class="panel" data-parent="#myAccordion">
			<table class="center tbl-header" cellpadding="0" cellspacing="0"
				border="0">
				<thead class="thead-dark">
					<tr>
						<th scope="col">NAME</th>
						<th scope="col">VALUE</th>
					</tr>
				</thead>
			</table>
			<div class="center tbl-content2" id="searchresult">
				<table class="center1 table-hover" cellpadding="0" cellspacing="0">
					{% for i in resultv %}
					<tr>
						{% for j in i %}
						<td>{{j}}</td> {% endfor %}
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
</div>
<script>
		var acc = document.getElementsByClassName("accordion");
		var i;
		for (i = 0; i < acc.length; i++) {
			acc[i].addEventListener("click", function() {
				this.classList.toggle("active");
				var panel = this.nextElementSibling;
			/* 	if (panel.style.display === "block") {
					panel.style.display = "none";
				} else {
					panel.style.display = "block";
				} */
				 if (panel.style.maxHeight){
				      panel.style.maxHeight = null;
				    } else {
				      panel.style.maxHeight = panel.scrollHeight + "px";
				    } 
			});
		}
	</script> 
	
	<script>
		function goBack() {
			window.history.back();
		}
	</script>

</body>
</html>